DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(255) NOT NULL,
  COMPANY VARCHAR(255)
);

INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY) VALUES ( 1, 'user1', 'company1');
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY) VALUES ( 2, 'user2', 'company2');
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY) VALUES ( 3, 'user3', 'company3');
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY) VALUES ( 4, 'user4', 'company4');
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY) VALUES ( 5, 'user5', 'company5');