DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(255) NOT NULL,
  COMPANY VARCHAR(255)
);

INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY ) VALUES ( 1, 'user1', 'company1' );
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY ) VALUES ( 2, 'user2', 'company2' );
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY ) VALUES ( 3, 'user3', 'company3' );
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY ) VALUES ( 4, 'user4', 'company4' );
INSERT INTO CUSTOMER( CUSTOMER_ID, CUSTOMER_NAME, COMPANY ) VALUES ( 5, 'user5', 'company5' );

DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
  USERNAME VARCHAR(50) PRIMARY KEY,
  PASSWORD VARCHAR(4000) NOT NULL,
  ROLE VARCHAR(50)
);
-- password : password
INSERT INTO USER( USERNAME, PASSWORD, ROLE ) VALUES ( 'admin', '$2a$10$53YS9u5iWfTw8Ld0v3tM1OKJvg/KDzCzluncqPPocb5X8LsiYgnGO', 'ADMIN' );
INSERT INTO USER( USERNAME, PASSWORD, ROLE ) VALUES ( 'user', '$2a$10$53YS9u5iWfTw8Ld0v3tM1OKJvg/KDzCzluncqPPocb5X8LsiYgnGO', 'USER' );